patients.msg =Welcome to the patients Prod application
patients.build-version=12

patients.mailDetails.hostName=prod-patients@jcb826.com
patients.mailDetails.port=9010
patients.mailDetails.from=titi@bankapp.com
patients.mailDetails.subject=Your patients Details from Production Environment

patients.activeBranches[0]=Hyderabad
patients.activeBranches[1]=Paris
patients.activeBranches[2]=NewYork
