webapp.msg =Welcome to the webapp Prod application
webapp.build-version=12

webapp.mailDetails.hostName=prod-webapp@jcb826.com
webapp.mailDetails.port=9010
webapp.mailDetails.from=titi@bankapp.com
webapp.mailDetails.subject=Your webapp Details from Production Environment

webapp.activeBranches[0]=Hyderabad
webapp.activeBranches[1]=Paris
webapp.activeBranches[2]=NewYork
